--[[
	This application is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    The applications is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with the applications.  If not, see <http://www.gnu.org/licenses/>.
--]]

--
-- The localization information present within this file is automatically
-- packaged by the CurseForge packager.
--
-- Incorrect or missing translations can be updated here:
-- http://war.curseforge.com/projects/pure/localization/
--

local T = LibStub("WAR-AceLocale-3.0"):NewLocale("Pure", "frFR")
if not T then return end

T["About Pure"] = L"À propos de Pure"
T["Action Point Format:"] = L"Format des Points d'Action :"
T["Action Point Texture:"] = L"Texture des Points d'Action :"
T["Action Points Texture Color"] = L"Couleur de la Texture des Points d'Action"
T["Active Profile:"] = L"Profil Actif :"
T["Alpha"] = L"Alpha"
T["Anchor Column Offset:"] = L"Décalage de la Colonne d'Ancrage :"
T["Anchor Row Offset:"] = L"Décalage de la Ligne d'Ancrage :"
T["Apply"] = L"Appliquer"
T["Archtype:"] = L"Archétype :"
T["Archtypes"] = L"Archétypes"
T["Are you sure?"] = L"Es-tu sûr ?"
T["Background"] = L"Arrière-plan"
T["Blue"] = L"Bleu"
T["Bottom"] = L"En bas"
T["Cancel"] = L"Annuler"
T["Cast Pet Heal On Click"] = L"Lancer le Soin du Familier en cliquant"
T["Clear Friendly Target On Click"] = L"Effacer la Cible Amicale en cliquant"
T["Click Through Unit Frame"] = L"Clic à travers la Fenêtre d'Unité"
T["Close"] = L"Fermer"
T["Colors"] = L"Couleurs"
T["Coming Soon!"] = L"Bientôt disponible !"
T["Configure Class/Archtypes:"] = L"Configurer Classes/Archétypes :"
T["Copy Settings From:"] = L"Copier les Paramètres de :"
T["Current Hitpoints:"] = L"Points de Vie Actuels :"
T["Current Profile:"] = L"Profil Actuel :"
T["Default"] = L"Par défaut"
T["Direction From Target"] = L"Direction depuis la Cible"
T["Dispel Highlighting"] = L"Surbrillance de Dissipation"
T["Distance"] = L"Distance"
T["Distance From Target"] = L"Distance de la Cible"
T["Down"] = L"Vers le bas"
T["Effect Anchor:"] = L"Ancrage des Effets :"
T["Effect Columns:"] = L"Colonnes des Effets :"
T["Effect Frame Alpha"] = L"Transparence du Cadre des Effets"
T["Effect Frame Font Alpha"] = L"Transparence de la Police du Cadre des Effets"
T["Effect Height:"] = L"Hauteur de l'Effet :"
T["Effect Rows:"] = L"Lignes d'Effets :"
T["Effect Width:"] = L"Largeur de l'Effet :"
T["Effects"] = L"Effets"
T["Enable Class Archtype Coloring"] = L"Activer la Couleur d'Archétype de Classe"
T["Enable Class Archtype Coloring - Hitpoints"] = L"Activer la Couleur d'Archétype - Points de Vie"
T["Enable Class Archtype Coloring - Name"] = L"Activer la Couleur d'Archétype - Nom"
T["Enable Dispel Highlighting"] = L"Activer la Surbrillance de Dissipation"
T["Enable Effect Tracker"] = L"Activer le Suivi des Effets"
T["Enable Friendly Target HUD"] = L"Activer le HUD de la Cible Amicale"
T["Enable Friendly Target HUD Unit Frame"] = L"Activer le Cadre d'Unité HUD pour Cible Amicale"
T["Enable Friendly Target Unit Frame"] = L"Activer le Cadre d'Unité de la Cible Amicale"
T["Enable Group Pet Unit Frame"] = L"Activer le Cadre d'Unité pour le Familier de Groupe"
T["Enable Group Unit Frame"] = L"Activer le Cadre d'Unité de Groupe"
T["Enable Hostile Target HUD"] = L"Activer le HUD de la Cible Hostile"
T["Enable Hostile Target HUD Unit Frame"] = L"Activer le Cadre d'Unité HUD pour Cible Hostile"
T["Enable Hostile Target Unit Frame"] = L"Activer le Cadre d'Unité de la Cible Hostile"
T["Enable Player Pet Target Unit Frame"] = L"Activer le Cadre d'Unité de la Cible du Familier du Joueur"
T["Enable Player Pet Unit Frame"] = L"Activer le Cadre d'Unité du Familier du Joueur"
T["Enable Player Unit Frame"] = L"Activer le Cadre d'Unité du Joueur"
T["Enable Pure"] = L"Activer Pure"
T["Enable Target Highlighting"] = L"Activer la Surbrillance de Cible"
T["Format:"] = L"Format :"
T["Formatting"] = L"Formatage"
T["Friendly Target"] = L"Cible Amicale"
T["Friendly Target HUD"] = L"HUD de la Cible Amicale"
T["Friendly Target HUD:"] = L"HUD de la Cible Amicale :"
T["Friendly Target:"] = L"Cible Amicale :"
T["General"] = L"Général"
T["Green"] = L"Vert"
T["Group"] = L"Groupe"
T["Group Leader Indicator:"] = L"Indicateur de Chef de Groupe :"
T["Group Pet"] = L"Familier de Groupe"
T["Group Pet Window"] = L"Fenêtre du Familier de Groupe"
T["Group Pet:"] = L"Familier de Groupe :"
T["Group Window"] = L"Fenêtre de Groupe"
T["Group:"] = L"Groupe :"
T["Growth Direction:"] = L"Direction de Croissance :"
T["Hit Point Format:"] = L"Format des Points de Vie :"
T["Hit Point Texture:"] = L"Texture des Points de Vie :"
T["Hit Points Texture Color"] = L"Couleur de la Texture des Points de Vie"
T["Horizontal Growth Offset:"] = L"Décalage Horizontal de Croissance :"
T["Hostile Target"] = L"Cible Hostile"
T["Hostile Target HUD"] = L"HUD de la Cible Hostile"
T["Hostile Target HUD:"] = L"HUD de la Cible Hostile :"
T["Hostile Target:"] = L"Cible Hostile :"
T["Left"] = L"Gauche"
T["Morale Color"] = L"Couleur de la Morale"
T["NOTE: Profile changes take effect immediately!"] = L"REMARQUE : Les changements de profil prennent effet immédiatement !"
T["None"] = L"Aucun"
T["Offline"] = L"Hors ligne"
T["Open Parties Window"] = L"Ouvrir la Fenêtre des Groupes"
T["Overlay"] = L"Superposition"
T["Pet Target"] = L"Cible du Familier"
T["Player"] = L"Joueur"
T["Player:"] = L"Joueur :"
T["Player Pet"] = L"Familier du Joueur"
T["Player Pet:"] = L"Familier du Joueur :"
T["Player Pet Target"] = L"Cible du Familier du Joueur"
T["Player Pet Target:"] = L"Cible du Familier du Joueur :"
T["Popup"] = L"Popup"
T["Profiles"] = L"Profils"
T["Pure %s initialized."] = L"Pure %s initialisé."
T["Pure - Configuration"] = L"Pure - Configuration"
T["Red"] = L"Rouge"
T["Reset Profile"] = L"Réinitialiser le Profil"
T["Revert"] = L"Réinitialiser"
T["Right"] = L"Droite"
T["RvR Flag Color"] = L"Couleur du Drapeau RvR"
T["Secondary"] = L"Secondaire"
T["Set Active Profile:"] = L"Définir le Profil Actif :"
T["Show Class Names"] = L"Afficher les Noms de Classe"
T["Show Effect Durations"] = L"Afficher la Durée des Effets"
T["Show In Scenarios"] = L"Afficher dans les Scénarios"
T["Show In Warband"] = L"Afficher dans l'Équipe"
T["Show Mythic Style Border"] = L"Afficher la Bordure de Style Mythique"
T["Show Player In Group"] = L"Afficher le Joueur dans le Groupe"
T["Show Self Cast Effects Only"] = L"Afficher seulement les Effets Lancés par Soi-même"
T["Show Sigil Requirement"] = L"Afficher la Condition du Sceau"
T["Show When In Siege Engine"] = L"Afficher en Machine de Siège"
T["Show When Out Of Combat"] = L"Afficher Hors Combat"
T["Target"] = L"Cible"
T["Target Highlighting"] = L"Surbrillance de la Cible"
T["Templates"] = L"Modèles"
T["Textures"] = L"Textures"
T["Top"] = L"En haut"
T["Unit Frame Alpha"] = L"Transparence du Cadre d'Unité"
T["Unit Frame Font Alpha"] = L"Transparence de la Police du Cadre d'Unité"
T["Unit Frame Templates"] = L"Modèles de Cadre d'Unité"
T["Up"] = L"Vers le haut"
T["Use Squared archtype coloring (Requires Squared)"] = L"Utiliser la couleur d'archétype en Carré (nécessite Carré)"
T["Vertical Growth Offset:"] = L"Décalage de Croissance Vertical :"
T["WARNING: Clicking this button will restore the current profile back to default values!"] = L"ATTENTION : Cliquer sur ce bouton réinitialisera le profil actuel aux valeurs par défaut !"
