function AbandonQuest()   end
function AcceptTrade()   end
function ActionButtonGroupGetIcon()   end
function ActionButtonGroupGetId()   end
function ActionButtonGroupGetShowing()   end
function ActionButtonGroupSetIcon()   end
function ActionButtonGroupSetId()   end
function ActionButtonGroupSetNumButtons()   end
function ActionButtonGroupSetShowing()   end
function ActionButtonGroupSetText()   end
function ActionButtonGroupSetTimeAbbreviations()   end
function ActionButtonGroupSetTimeFormat()   end
function ActionButtonGroupSetTimer()   end
function ActionButtonGroupSetTintColor()   end
function ActivateTactics()   end
function AddActiveTactic()   end
function AddBinding()   end
function AddCraftingContainer()   end
function AddCraftingItem()   end
function AddItemEnhancement()   end
function AddSelectedReward()   end
function AddTemporaryIgnore()   end
function AnimatedImageSetPlaySpeed()   end
function AnimatedImageSetTexture()   end
function AnimatedImageStartAnimation()   end
function AnimatedImageStopAnimation()   end
function ApplyPlayerVariation()   end
function ArchMage_GetPointsString()   end
function AssignLootItem()   end
function AttachTrophyToLocation()   end
function AttachWindowToWorldObject()   end
function AutoEquipItem()   end
function BarbershopHaveFeaturesChanged()   end
function BarbershopResetFeatures()   end
function BarbershopSetFeature()   end
function BarbershopSubmitFeatures()   end
function BeginItemEnhancement()   end
function BroadcastEvent()   end
function BuildSiegeWeapon()   end
function BuildTableFromCSV()   end
function ButtonGetCheckButtonFlag()   end
function ButtonGetDisabledFlag()   end
function ButtonGetHighlightFlag()   end
function ButtonGetPressedFlag()   end
function ButtonGetStayDownFlag()   end
function ButtonGetText()   end
function ButtonGetTextDimensions()   end
function ButtonSetCheckButtonFlag()   end
function ButtonSetDisabledFlag()   end
function ButtonSetHighlightFlag()   end
function ButtonSetPressedFlag()   end
function ButtonSetStayDownFlag()   end
function ButtonSetText()   end
function ButtonSetTextColor()   end
function ButtonSetTexture()   end
function ButtonSetTextureSlice()   end
function BuyAuction()   end
function BuyBackpackSlots()   end
function BuyBankSlots()   end
function BuyCareerPackage()   end
function BuyTradeSkill()   end
function CHAT_DEBUG()   end
function CacheData()   end
function CanPlayCinematic()   end
function CanUseDyeItem()   end
function CancelAuction()   end
function CancelKeepUpgrade()   end
function CancelSpell()   end
function CancelTrade()   end
function ChangeTrade()   end
function CharacterSettingsClearRunningDefaultUiFlag()   end
function CharacterSettingsCreateUiProfile()   end
function CharacterSettingsExportUiProfile()   end
function CharacterSettingsGetAllUiProfiles()   end
function CharacterSettingsGetData()   end
function CharacterSettingsGetOtherCharactersUsingProfile()   end
function CharacterSettingsHandleDeletedCharacter()   end
function CharacterSettingsImportUiProfile()   end
function CharacterSettingsRemoveUiProfile()   end
function CharacterSettingsRenameUiProfile()   end
function CharacterSettingsSetActiveUiProfile()   end
function CharacterSettingsSetUiProfileShared()   end
function CircleImageMoveRotationCenter()   end
function CircleImageSetFillParams()   end
function CircleImageSetRotation()   end
function CircleImageSetTexture()   end
function CircleImageSetTextureScale()   end
function CircleImageSetTextureSlice()   end
function ClearActiveTactics()   end
function ClearCursor()   end
function ClearPQLootData()   end
function ClearSelectedRewards()   end
function ClearTarget()   end
function ColorPickerAddColor()   end
function ColorPickerAddColorAtPosition()   end
function ColorPickerClear()   end
function ColorPickerCreateWithColorTable()   end
function ColorPickerGetColorAtPoint()   end
function ColorPickerGetColorById()   end
function ColorPickerGetColorSize()   end
function ColorPickerGetColorSpacing()   end
function ColorPickerGetCoordinatesForColor()   end
function ColorPickerGetTexDims()   end
function ComboBoxAddMenuItem()   end
function ComboBoxClearMenuItems()   end
function ComboBoxExternalOpenMenu()   end
function ComboBoxGetDisabledFlag()   end
function ComboBoxGetSelectedMenuItem()   end
function ComboBoxGetSelectedText()   end
function ComboBoxIsMenuOpen()   end
function ComboBoxSetDisabledFlag()   end
function ComboBoxSetSelectedMenuItem()   end
function CommandPet()   end
function CommandPetDoAbility()   end
function CommandPetToggleAbility()   end
function ConfirmedTransferGuild()   end
function CooldownDisplaySetCooldown()   end
function CreateAuction()   end
function CreateConversationLog()   end
function CreateHyperLink()   end
function CreateMapInstance()   end
function CreateWindow()   end
function CreateWindowFromTemplate()   end
function CurrentEventsGetList()   end
function CurrentEventsGetTimers()   end
function CurrentEventsJumpToEvent()   end
function CurrentEventsUpdate()   end
function DEBUG()   end
function DUMP_TABLE()   end
function DUMP_TABLE_TO()   end
function DestroyItem()   end
function DestroyWindow()   end
function DetachWindowFromWorldObject()   end
function DoesWindowExist()   end
function DonateToAltar()   end
function DyeMerchantPreview()   end
function DyeMerchantPreviewAll()   end
function DyePreview()   end
function DynamicImageClearCustomShader()   end
function DynamicImageHasTexture()   end
function DynamicImageSetCustomShader()   end
function DynamicImageSetRotation()   end
function DynamicImageSetTexture()   end
function DynamicImageSetTextureDimensions()   end
function DynamicImageSetTextureOrientation()   end
function DynamicImageSetTextureScale()   end
function DynamicImageSetTextureSlice()   end
function EA_Window_HelpGetEntryData()   end
function EA_Window_HelpGetFAQEntryData()   end
function EA_Window_HelpGetFAQTopicList()   end
function EA_Window_HelpGetHelpTipsList()   end
function EA_Window_HelpGetTopicList()   end
function ENABLE_TRACE()   end
function END_FUNCTION()   end
function ERROR()   end
function ERROR_TRACE()   end
function EnableAlert()   end
function EnableRRQUpdates()   end
function EndItemEnhancement()   end
function FireAltarAbility()   end
function ForceProcessAllWindowAnchors()   end
function ForceUpdateWorldObjectWindow()   end
function FormatLastLoginTime()   end
function FuseItemEnhancements()   end
function GetAFKFlag()   end
function GetAbilityActionPointCost()   end
function GetAbilityCastTime()   end
function GetAbilityCooldown()   end
function GetAbilityData()   end
function GetAbilityDesc()   end
function GetAbilityDescription()   end
function GetAbilityName()   end
function GetAbilityRanges()   end
function GetAbilityRequirements()   end
function GetAbilityTable()   end
function GetAbilityUpgradeRank()   end
function GetAccountData()   end
function GetActionIdFromName()   end
function GetActionNameFromId()   end
function GetActionsForButtonCombination()   end
function GetActiveObjectivesData()   end
function GetActiveTactics()   end
function GetAdvisorFlag()   end
function GetAllianceMemberCounts()   end
function GetAllianceMemberData()   end
function GetAndClearPartyMemberDirtyFlag()   end
function GetAndClearWarbandMemberDirtyFlag()   end
function GetAreaData()   end
function GetBankData()   end
function GetBannerConfigurationData()   end
function GetBattlegroupMemberData()   end
function GetBindingsForAction()   end
function GetBlockedAbilities()   end
function GetBolsterBuddy()   end
function GetBonus()   end
function GetBonusIsSalvagable()   end
function GetBraggingRights()   end
function GetBuffs()   end
function GetButtonName()   end
function GetBuyBackData()   end
function GetCachedData()   end
function GetCampaignCityData()   end
function GetCampaignPairingData()   end
function GetCampaignZoneData()   end
function GetCareerLine()   end
function GetCareerResource()   end
function GetChapterName()   end
function GetChapterShortName()   end
function GetChatChannelNames()   end
function GetChatString()   end
function GetCheckForCircularDependencies()   end
function GetChoiceRewardsData()   end
function GetCityInstanceId()   end
function GetCityName()   end
function GetCityNameForRealm()   end
function GetCityRatingForCityId()   end
function GetClusterAnchorPoint()   end
function GetComputerTime()   end
function GetCraftingBackPackSlots()   end
function GetCraftingData()   end
function GetCraftingItemData()   end
function GetCreditsData()   end
function GetCultivationInfo()   end
function GetCurrencyItemData()   end
function GetCurrentEnhancementItemData()   end
function GetDPSModifier()   end
function GetDatabaseAbilityData()   end
function GetDatabaseGuildData()   end
function GetDatabaseItemData()   end
function GetDatabaseQuestData()   end
function GetDesiredInteractAction()   end
function GetDyeMerchantData()   end
function GetDyeName()   end
function GetDyeNameString()   end
function GetDyeTintMasks()   end
function GetEpochTime()   end
function GetEquipmentData()   end
function GetEquippedItemVisible()   end
function GetExperienceData()   end
function GetFirstDayOfWeek()   end
function GetFlightMasterData()   end
function GetFormatStringFromTable()   end
function GetFrame()   end
function GetFriendsList()   end
function GetGameDataObjectives()   end
function GetGameTime()   end
function GetGivenRewardsData()   end
function GetGroupData()   end
function GetGroupMemberStatusData()   end
function GetGuildAdvancementData()   end
function GetGuildAppointmentData()   end
function GetGuildMemberData()   end
function GetGuildPermissionData()   end
function GetGuildPollData()   end
function GetGuildSignupData()   end
function GetGuildString()   end
function GetGuildTacticsRespecCost()   end
function GetHelpString()   end
function GetHelpTipStrings()   end
function GetHeraldryBestOptions()   end
function GetHeraldryConfigurationData()   end
function GetHeraldryCost()   end
function GetHeraldryResetCost()   end
function GetHotbarCooldown()   end
function GetHotbarData()   end
function GetHotbarGlowLevels()   end
function GetHotbarIcon()   end
function GetHotbarName()   end
function GetHotbarPage()   end
function GetIconData()   end
function GetIgnoreList()   end
function GetInfluenceData()   end
function GetInputLanguageString()   end
function GetInspectionBragData()   end
function GetInspectionData()   end
function GetInventoryItemData()   end
function GetInventorySlotStackCount()   end
function GetItemStackCount()   end
function GetKeepData()   end
function GetKeepName()   end
function GetKeepUpgradeDesc()   end
function GetKeepUpgradeName()   end
function GetLiveEventData()   end
function GetLiveEventList()   end
function GetLiveEventTasks()   end
function GetLoadLuaDebugLibrary()   end
function GetLocationsForTrophies()   end
function GetLootRollData()   end
function GetMacrosData()   end
function GetMailString()   end
function GetMapIconData()   end
function GetMapPointData()   end
function GetMapTextPoints()   end
function GetMonthName()   end
function GetMoraleBarData()   end
function GetMoraleCooldown()   end
function GetMoralePercentForLevel()   end
function GetNameForObject()   end
function GetNewbieGuildFlag()   end
function GetNumAssignedBearers()   end
function GetNumBrassPerGold()   end
function GetNumBrassPerSilver()   end
function GetNumGroupmates()   end
function GetNumTacticsSlots()   end
function GetObjectiveName()   end
function GetOpenPartyFullList()   end
function GetOpenPartyNotificationList()   end
function GetOpenPartyWorldList()   end
function GetOverflowData()   end
function GetOverheadMapZoomLevel()   end
function GetPQLootWinners()   end
function GetPQTopContributors()   end
function GetPlayerEnergy()   end
function GetPlayerMoraleLevel()   end
function GetPlayerVariation()   end
function GetPregameString()   end
function GetPregameStringFormat()   end
function GetQuestData()   end
function GetQuestItemData()   end
function GetQuestPointConditions()   end
function GetRRQData()   end
function GetRealmName()   end
function GetReleventAreaIndex()   end
function GetRewardPools()   end
function GetSalvagingDifficulty()   end
function GetScenarioLobbyDesc()   end
function GetScenarioName()   end
function GetScenarioQueueData()   end
function GetScenarioScoreDesc()   end
function GetScreenResolution()   end
function GetSearchList()   end
function GetServerList()   end
function GetSiegePadBuildData()   end
function GetSiegeWeaponControlData()   end
function GetSiegeWeaponUsersData()   end
function GetSingleItem()   end
function GetSocialPreferenceData()   end
function GetSpecializationPathDescription()   end
function GetSpecializationPathName()   end
function GetStoreCategories()   end
function GetStoreData()   end
function GetString()   end
function GetStringFormat()   end
function GetStringFormatFromTable()   end
function GetStringFromTable()   end
function GetTacticsSet()   end
function GetTargetStatesData()   end
function GetTemplateWindowDimensions()   end
function GetTimeStamp()   end
function GetTimeUntilAutoRespawn()   end
function GetTodaysDate()   end
function GetTomeAlertsData()   end
function GetTradeItemData()   end
function GetTradeSkillLevel()   end
function GetTradeskillIcon()   end
function GetTrophyData()   end
function GetUnderdogRatings()   end
function GetUpdatedTargets()   end
function GetUseLuaErrorHandling()   end
function GetWarbandMemberStatus()   end
function GetWeekDayName()   end
function GetYearMonthName()   end
function GetZoneAreaName()   end
function GetZoneIDList()   end
function GetZoneLargestHotspotSize()   end
function GetZoneName()   end
function GetZoneObjectivesData()   end
function GetZonePairing()   end
function GetZoneRanksForCurrentRealm()   end
function GetZoneTier()   end
function GetZoneTransitionPoints()   end
function GroupInviteAccept()   end
function GroupInviteCallback()   end
function GroupInviteDecline()   end
function GuildGetRewards()   end
function GuildRecruitmentProfileGetData()   end
function GuildRecruitmentProfileSetData()   end
function GuildRecruitmentSearch()   end
function HorizontalScrollWindowGetOffset()   end
function HorizontalScrollWindowSetOffset()   end
function HorizontalScrollWindowUpdateScrollRect()   end
function HorizontalScrollbarGetLineSize()   end
function HorizontalScrollbarGetMaxScrollPosition()   end
function HorizontalScrollbarGetPageSize()   end
function HorizontalScrollbarGetScrollPosition()   end
function HorizontalScrollbarSetLineSize()   end
function HorizontalScrollbarSetMaxScrollPosition()   end
function HorizontalScrollbarSetPageSize()   end
function HorizontalScrollbarSetScrollPosition()   end
function InitializeDialogs()   end
function InitiateTrade()   end
function InteractGetBaseInteractionData()   end
function InteractSelect()   end
function IsAbilityEnabled()   end
function IsAbilityToggledOn()   end
function IsInternalBuild()   end
function IsMacClient()   end
function IsModifierKey()   end
function IsPlayerInitialized()   end
function IsPlayerMainAssist()   end
function IsPlayerSolo()   end
function IsShowingCloakHeraldry()   end
function IsTargetValid()   end
function IsWarBandActive()   end
function ItemContainerLootItem()   end
function JoinScenarioGroup()   end
function LCDBitmapSetImage()   end
function LCDButtonPressed()   end
function LCDCreateBitmap()   end
function LCDCreatePage()   end
function LCDCreateProgressBar()   end
function LCDCreateStaticText()   end
function LCDDestroyPage()   end
function LCDGetLocation()   end
function LCDGetSize()   end
function LCDProgressBarGetProgress()   end
function LCDProgressBarSetProgress()   end
function LCDRegisterEventHandler()   end
function LCDSetButtonHandler()   end
function LCDSetLocation()   end
function LCDSetSize()   end
function LCDShowPage()   end
function LCDStaticTextSetText()   end
function LCDUnregisterEventHandler()   end
function LCDUnsetButtonHandler()   end
function LabelGetFont()   end
function LabelGetIgnoreFormattingTags()   end
function LabelGetLinkColor()   end
function LabelGetText()   end
function LabelGetTextColor()   end
function LabelGetTextDimensions()   end
function LabelGetWordWrap()   end
function LabelSetFont()   end
function LabelSetIgnoreFormattingTags()   end
function LabelSetLinkColor()   end
function LabelSetText()   end
function LabelSetTextAlign()   end
function LabelSetTextColor()   end
function LabelSetWordWrap()   end
function LeaveScenarioGroup()   end
function ListBoxGetDataIndex()   end
function ListBoxSetDataTable()   end
function ListBoxSetDisplayOrder()   end
function ListBoxSetVisibleRowCount()   end
function LoadResources()   end
function LoadStringTable()   end
function LoadingScreenGetCurrentData()   end
function LoadingScreenGetPatchNotesData()   end
function LogDisplayAddLog()   end
function LogDisplayGetFilterColor()   end
function LogDisplayGetFilterState()   end
function LogDisplayGetFont()   end
function LogDisplayGetShowFilterName()   end
function LogDisplayGetShowLogName()   end
function LogDisplayGetShowTimestamp()   end
function LogDisplayGetStringFromCursorPos()   end
function LogDisplayGetTextFadeTime()   end
function LogDisplayHideFilterSubType()   end
function LogDisplayIsScrollbarActive()   end
function LogDisplayIsScrolledToBottom()   end
function LogDisplayIsScrolledToTop()   end
function LogDisplayRemoveLog()   end
function LogDisplayResetLineFadeTime()   end
function LogDisplayScrollToBottom()   end
function LogDisplayScrollToTop()   end
function LogDisplaySetEntryLimit()   end
function LogDisplaySetFilterColor()   end
function LogDisplaySetFilterState()   end
function LogDisplaySetFont()   end
function LogDisplaySetShowFilterName()   end
function LogDisplaySetShowLogName()   end
function LogDisplaySetShowTimestamp()   end
function LogDisplaySetTextFadeTime()   end
function LogLuaMessage()   end
function LootAllItems()   end
function LootItem()   end
function LootRollOptOut()   end
function MapGetChildMaps()   end
function MapGetCoordinatesForPoint()   end
function MapGetParentMap()   end
function MapGetPlayerLocationMaps()   end
function MapGetPointForCoordinates()   end
function MapSetMapView()   end
function MapSetPinFilter()   end
function MapSetPinGutter()   end
function ModuleAddSavedVariable()   end
function ModuleInitialize()   end
function ModuleLoad()   end
function ModuleRemoveSavedVariable()   end
function ModuleSetEnabled()   end
function ModulesGetData()   end
function ModulesInitializeAllEnabled()   end
function ModulesLoadFromDirectory()   end
function ModulesLoadFromListFile()   end
function ModulesSaveSettings()   end
function MoveWindowToWorldObject()   end
function NamingConflictRequestNewName()   end
function NewChatBubbleData()   end
function NewChatBubbleGroupData()   end
function NewColor()   end
function NewCursorData()   end
function NewGuildSortData()   end
function NewModSortData()   end
function NewQuestSortData()   end
function NewSortData()   end
function NewStateData()   end
function NewTargetData()   end
function NewTomeStat()   end
function NewWorldEventTextData()   end
function NifDisplaySetTranslation()   end
function OpenURL()   end
function PQLootItem()   end
function PageWindowAddPageBreak()   end
function PageWindowAddSplitableWindow()   end
function PageWindowClearPageBreaks()   end
function PageWindowClearSplitableWindows()   end
function PageWindowGetCurrentPage()   end
function PageWindowGetNumPages()   end
function PageWindowGetNumPagesDisplayed()   end
function PageWindowRemovePageBreak()   end
function PageWindowRemoveSplitableWindow()   end
function PageWindowSetCurrentPage()   end
function PageWindowUpdatePages()   end
function PerformCrafting()   end
function PlayInteractSound()   end
function PlaySound()   end
function PregameBlockMouseOver()   end
function PregameGetCharacterSelectNumPages()   end
function PregameGetCharacterSelectPage()   end
function PregameGetEULAFileName()   end
function PregameGetPreSelectedServerRealm()   end
function PregameGetQuickStartLabels()   end
function PregameGetROCFileName()   end
function PregameGetRealmLimit()   end
function PregameGetServerRealmBonuses()   end
function PregameHasEULAChanged()   end
function PregameHasROCChanged()   end
function PregamePlayCinematic()   end
function PregameRandomFeatures()   end
function PregameSetCharacterSelectPage()   end
function PregameSetFeature()   end
function PregameSetPreSelectedServerRealm()   end
function PregameSetServerRealmBonuses()   end
function PregameStopCinematic()   end
function PurchaseKeepUpgrade()   end
function RefundRenownPoints()   end
function RefundSpecialtyPoints()   end
function RegisterEventHandler()   end
function RegisterWindowSet()   end
function RemoveActiveTactic()   end
function RemoveAllBindings()   end
function RemoveBinding()   end
function RemoveCraftingItem()   end
function RemoveEffect()   end
function RemoveItemEnhancement()   end
function RemoveMapInstance()   end
function RemoveSelectedReward()   end
function RemoveTargetEffect()   end
function RemoveTomeAlert()   end
function RepairSiegeWeapon()   end
function RequestEquipTrophy()   end
function RequestItemSet()   end
function RequestMoveItem()   end
function RequestSalvageItem()   end
function ResetGuildHeraldry()   end
function RespecGuildTactics()   end
function RestoreDefaultBindings()   end
function RevertAllDyePreview()   end
function RevertDyePreview()   end
function RevertPlayerVariation()   end
function SHOW_STACK_TRACE()   end
function SIMPLE_STACK_TRACE()   end
function START_FUNCTION()   end
function SaveTacticsSet()   end
function ScaleInterface()   end
function ScrollWindowGetOffset()   end
function ScrollWindowSetOffset()   end
function ScrollWindowUpdateScrollRect()   end
function SelectEventRewards()   end
function SelectInfluenceReward()   end
function SelectItemRollChoice()   end
function SelectServer()   end
function SendAuctionSearch()   end
function SendBannerConfigurationData()   end
function SendBugReport()   end
function SendChatText()   end
function SendCloseCrafting()   end
function SendCustomizeItemIcon()   end
function SendGuildAllianceCommand()   end
function SendGuildAppointmentData()   end
function SendGuildVaultCommand()   end
function SendHelpMessage()   end
function SendHeraldryConfigurationData()   end
function SendInitCrafting()   end
function SendMailboxCommand()   end
function SendOpenPartySearchRequest()   end
function SendOpenPartyWorldSearch()   end
function SendPlayerInspectionRequest()   end
function SendPlayerSearchRequest()   end
function SendSurveyResponse()   end
function SendUseItem()   end
function SetAdvisorFlag()   end
function SetBraggingRight()   end
function SetBraggingRightsCard()   end
function SetCareerMasteryImages()   end
function SetCheckForCircularDependencies()   end
function SetCursor()   end
function SetDesiredInteractAction()   end
function SetEquippedItemVisible()   end
function SetGroupAutoLootInRvR()   end
function SetGroupLootMode()   end
function SetGroupLootThreshold()   end
function SetGroupNeedMode()   end
function SetGuildHeraldryScene()   end
function SetGuildStandardScene()   end
function SetHardwareCursor()   end
function SetHotbarData()   end
function SetHotbarPage()   end
function SetItemDragging()   end
function SetLiveEventTaskImage()   end
function SetLoadLuaDebugLibrary()   end
function SetMacroData()   end
function SetMoraleBarData()   end
function SetNamesAndTitlesFont()   end
function SetOpenPartyWorldInterests()   end
function SetOverheadMapZoomLevel()   end
function SetPlayerPortraitBackground()   end
function SetPlayerVariation()   end
function SetSelectedColumnColor()   end
function SetTargetPortraitBackground()   end
function SetTargetToSummon()   end
function SetTextureImage()   end
function SetTrackQuest()   end
function SetTrackQuestPin()   end
function SetUseLuaErrorHandling()   end
function Shaman_GetPointsString()   end
function ShareQuest()   end
function SiegeSetWindDirectionImage()   end
function SliderBarGetCurrentPosition()   end
function SliderBarGetDisabledFlag()   end
function SliderBarSetCurrentPosition()   end
function SliderBarSetDisabledFlag()   end
function StatusBarGetCurrentValue()   end
function StatusBarGetMaximumValue()   end
function StatusBarSetBackgroundTint()   end
function StatusBarSetCurrentValue()   end
function StatusBarSetForegroundTint()   end
function StatusBarSetMaximumValue()   end
function StatusBarStopInterpolating()   end
function StringSplit()   end
function StringToWString()   end
function StringsCompare()   end
function SwapActiveTactic()   end
function SwitchStoreCategories()   end
function Swordmaster_GetPointsString()   end
function TRACE()   end
function TakeScreenShot()   end
function TextEditBoxGetAllowEditing()   end
function TextEditBoxGetFont()   end
function TextEditBoxGetHistory()   end
function TextEditBoxGetMaxChars()   end
function TextEditBoxGetText()   end
function TextEditBoxGetTextColor()   end
function TextEditBoxInsertText()   end
function TextEditBoxSelectAll()   end
function TextEditBoxSetAllowEditing()   end
function TextEditBoxSetFont()   end
function TextEditBoxSetHandleKeyDown()   end
function TextEditBoxSetHistory()   end
function TextEditBoxSetMaxChars()   end
function TextEditBoxSetText()   end
function TextEditBoxSetTextColor()   end
function TextLogAddEntry()   end
function TextLogAddFilterType()   end
function TextLogAddSingleByteEntry()   end
function TextLogClear()   end
function TextLogCreate()   end
function TextLogDestroy()   end
function TextLogDisplayShowScrollbar()   end
function TextLogGetEnabled()   end
function TextLogGetEntry()   end
function TextLogGetFilterEnabled()   end
function TextLogGetIncrementalSaving()   end
function TextLogGetNumEntries()   end
function TextLogGetUpdateEventId()   end
function TextLogLoadFromFile()   end
function TextLogSaveLog()   end
function TextLogSetEnabled()   end
function TextLogSetEntryLimit()   end
function TextLogSetFilterEnabled()   end
function TextLogSetIncrementalSaving()   end
function ToggleLanguageState()   end
function TomeGetAchievementsEntryData()   end
function TomeGetAchievementsSubTypeData()   end
function TomeGetAchievementsTOC()   end
function TomeGetBestiarySpeciesData()   end
function TomeGetBestiarySubTypeData()   end
function TomeGetBestiaryTOC()   end
function TomeGetCardData()   end
function TomeGetCardList()   end
function TomeGetHistoryAndLoreEntryData()   end
function TomeGetHistoryAndLoreTOC()   end
function TomeGetHistoryAndLoreZoneData()   end
function TomeGetItemRewardData()   end
function TomeGetItemRewardsList()   end
function TomeGetNoteworthyPersonsEntryData()   end
function TomeGetNoteworthyPersonsTOC()   end
function TomeGetNoteworthyPersonsZoneData()   end
function TomeGetOldWorldArmoryArmorSet()   end
function TomeGetOldWorldArmoryTOC()   end
function TomeGetOldWorldArmoryTierTOC()   end
function TomeGetPlayerTitleData()   end
function TomeGetPlayerTitlesAvailiableTypes()   end
function TomeGetPlayerTitlesTypeData()   end
function TomeGetSigilDisplayInfo()   end
function TomeGetSigilEntry()   end
function TomeGetSigilTOC()   end
function TomeGetTacticCounter()   end
function TomeGetTacticCounterRewardData()   end
function TomeGetTacticRewardData()   end
function TomeGetTacticRewardsList()   end
function TomeGetWarJournalAvailiableStorylines()   end
function TomeGetWarJournalEntryData()   end
function TomeGetWarJournalGlyphEntryForZone()   end
function TomeGetWarJournalStorylineData()   end
function TomeIsAchievementsEntryUnlocked()   end
function TomeIsAchievementsSubTypeUnlocked()   end
function TomeIsBestiarySpeciesUnlocked()   end
function TomeIsBestiarySubTypeUnlocked()   end
function TomeIsHistoryAndLoreEntryUnlocked()   end
function TomeIsNoteworthyPersonsEntryUnlocked()   end
function TomeIsPlayerTitleUnlocked()   end
function TomeIsWarJournalEntryUnlocked()   end
function TomeIsWarJournalStorylineUnlocked()   end
function TomeSetAchievementsSubTypeImage()   end
function TomeSetActivePlayerTitle()   end
function TomeSetBestiarySpeciesImage()   end
function TomeSetBestiarySubTypeImage()   end
function TomeSetWarJournalEntryImage()   end
function TomeSetWarJournalGlyphImage()   end
function TrainerHasSufficientRankFilter()   end
function TransferBetweenBackpacks()   end
function UnitInfo()   end
function UnloadStringTable()   end
function UnregisterEventHandler()   end
function UnsetOpenPartyWorldInterests()   end
function UpdateCraftingStatus()   end
function UpdateEnhancementDurations()   end
function UpgradeEquipment()   end
function UseEffect()   end
function VerticalScrollbarGetLineSize()   end
function VerticalScrollbarGetMaxScrollPosition()   end
function VerticalScrollbarGetPageSize()   end
function VerticalScrollbarGetScrollPosition()   end
function VerticalScrollbarSetLineSize()   end
function VerticalScrollbarSetMaxScrollPosition()   end
function VerticalScrollbarSetPageSize()   end
function VerticalScrollbarSetScrollPosition()   end
function VideoPlayerIsPlaying()   end
function WStringSplit()   end
function WStringToString()   end
function WStringsCompare()   end
function WStringsCompareIgnoreGrammer()   end
function WStringsRemoveGrammar()   end
function WideStringFromData()   end
function WindowAddAnchor()   end
function WindowAssignFocus()   end
function WindowClearAnchors()   end
function WindowForceProcessAnchors()   end
function WindowGameAction()   end
function WindowGetAlpha()   end
function WindowGetAnchor()   end
function WindowGetAnchorCount()   end
function WindowGetDimensions()   end
function WindowGetFontAlpha()   end
function WindowGetGameActionData()   end
function WindowGetHandleInput()   end
function WindowGetId()   end
function WindowGetLayer()   end
function WindowGetMovable()   end
function WindowGetMoving()   end
function WindowGetOffsetFromParent()   end
function WindowGetParent()   end
function WindowGetPopable()   end
function WindowGetResizing()   end
function WindowGetScale()   end
function WindowGetScreenPosition()   end
function WindowGetShowing()   end
function WindowGetTabOrder()   end
function WindowGetTintColor()   end
function WindowIsGameActionLocked()   end
function WindowIsSticky()   end
function WindowRegisterCoreEventHandler()   end
function WindowRegisterEventHandler()   end
function WindowResizeOnChildren()   end
function WindowRestoreDefaultSettings()   end
function WindowSetAlpha()   end
function WindowSetDimensions()   end
function WindowSetDrawWhenInterfaceHidden()   end
function WindowSetFontAlpha()   end
function WindowSetGameActionData()   end
function WindowSetGameActionTrigger()   end
function WindowSetHandleInput()   end
function WindowSetId()   end
function WindowSetLayer()   end
function WindowSetMovable()   end
function WindowSetMoving()   end
function WindowSetOffsetFromParent()   end
function WindowSetParent()   end
function WindowSetPopable()   end
function WindowSetRelativeScale()   end
function WindowSetResizing()   end
function WindowSetScale()   end
function WindowSetShowing()   end
function WindowSetTabOrder()   end
function WindowSetTintColor()   end
function WindowStartAlphaAnimation()   end
function WindowStartPositionAnimation()   end
function WindowStartScaleAnimation()   end
function WindowStopAlphaAnimation()   end
function WindowStopPositionAnimation()   end
function WindowStopScaleAnimation()   end
function WindowUnregisterCoreEventHandler()   end
function WindowUnregisterEventHandler()   end
function WorldToScreen()   end
function _LabelGetLinkColor()   end
function _LabelGetText()   end
function _LabelGetTextColor()   end
function _LabelGetTextDimensions()   end
function _WindowGetDimensions()   end
function _WindowGetShowing()   end
function booltostring()   end
function d()   end
function dt()   end
function luaAssert()   end
function towstring()   end