import { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Addon = { name: string; slug: string; version: string; category: string; tags: string[]; downloads: string; updated: string; description: string; status: string };
const addons: Addon[] = [
  { name: 'Enemy', slug: 'enemy', version: '2.9.6', category: 'Combat', tags: ['PvP', 'Combat'], downloads: '82.4k', updated: '16 hours ago', status: 'Active', description: 'Combat awareness suite with unit frames, marks, intercom, and fight information.' },
  { name: 'Pure', slug: 'pure', version: '1.8.6', category: 'Unit frames', tags: ['UI', 'Healing'], downloads: '43.6k', updated: '1 month ago', status: 'Active', description: 'Clean, configurable unit frames for players, targets, and group members.' },
  { name: 'LibSlash', slug: 'libslash', version: '3.0.0', category: 'Libraries', tags: ['Library'], downloads: '41.5k', updated: '1 year ago', status: 'Maintained', description: 'Shared slash-command library used by many Return of Reckoning addons.' },
  { name: 'GuardPack', slug: 'guardpack', version: '1.7.1', category: 'Warband', tags: ['Tank', 'Warband'], downloads: '29.9k', updated: '2 years ago', status: 'Maintained', description: 'Guard range, tether, and group tools for tanks and their partners.' },
  { name: 'WarBoard', slug: 'warboard', version: '5.3.9', category: 'UI', tags: ['UI', 'RvR'], downloads: '18.9k', updated: '6 months ago', status: 'Maintained', description: 'A flexible information bar for RvR, currency, time, influence, and more.' },
  { name: 'GCDsaver', slug: 'gcdsaver', version: '1.2.20', category: 'Action bars', tags: ['Combat', 'UI'], downloads: '8.8k', updated: '5 days ago', status: 'Active', description: 'Action-bar timing and global cooldown visibility for faster decisions.' },
  { name: 'MapPing', slug: 'mapping', version: '1.0.0', category: 'Maps', tags: ['RvR', 'Map'], downloads: '100', updated: '3 weeks ago', status: 'New', description: 'Synchronized map pings for coordinated RvR movement.' },
  { name: 'TomeTitan', slug: 'tometitan', version: '3.0.4', category: 'Tome of Knowledge', tags: ['Collection'], downloads: '5.8k', updated: '1 month ago', status: 'Maintained', description: 'Track Tome of Knowledge unlocks and collection progress.' },
];

function App() {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('All categories'); const [selected, setSelected] = useState<Addon | null>(null);
  const categories = ['All categories', ...Array.from(new Set(addons.map((addon) => addon.category)))];
  const filtered = useMemo(() => addons.filter((addon) => `${addon.name} ${addon.description} ${addon.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()) && (category === 'All categories' || addon.category === category)), [query, category]);
  return <div className="shell">
    <header className="topbar"><a className="brand" href="/"><span className="sigil">✦</span><span>The Emissary<small>RETURN OF RECKONING TOOLS</small></span></a><nav><a href="/">Tools</a><a className="active" href="/addons">Addons</a><a href="https://tools.idrinth.de/addons/">Legacy archive</a></nav><button className="login">Sign in to upload</button></header>
    <main><section className="intro"><div><p className="eyebrow">Community addon registry</p><h1>Find your next <em>advantage.</em></h1><p className="lede">Browse the tools that make life in Return of Reckoning clearer, faster, and more yours.</p></div><div className="author-card"><div className="author-mark">＋</div><div><strong>Are you an addon author?</strong><span>Sign in to submit a release or claim an existing project.</span></div><button onClick={() => alert('Author sign-in will connect to Discord or GitHub.')}>Author portal <span>→</span></button></div></section>
      <section className="toolbar"><label className="search"><span>⌕</span><input aria-label="Search addons" placeholder="Search addons, tags, or features" value={query} onChange={(event) => setQuery(event.target.value)} /></label><select aria-label="Filter by category" value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select><span className="count">{filtered.length} of 399 indexed releases</span></section>
      <section className="section-head"><div><p className="eyebrow">The registry</p><h2>Recently updated</h2></div><div className="sort">Updated <span>⌄</span></div></section>
      <section className="grid">{filtered.map((addon) => <article className="addon-card" key={addon.slug} onClick={() => setSelected(addon)}><div className="card-top"><div className="addon-icon">{addon.name.slice(0, 1)}</div><span className={`status ${addon.status.toLowerCase()}`}>{addon.status}</span></div><h3>{addon.name}</h3><p>{addon.description}</p><div className="tags">{addon.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><footer><span>v{addon.version}</span><span>{addon.downloads} downloads</span><span>{addon.updated}</span></footer></article>)}</section>{filtered.length === 0 && <div className="empty">No addons match those filters. Try a broader search.</div>}<footer className="rights"><span>Uploads require author permission and attribution.</span><a href="/addons/content-rights">Content rights</a><a href="/addons/security">Security &amp; privacy</a></footer></main>
    {selected && <div className="backdrop" onClick={() => setSelected(null)}><aside className="detail" onClick={(event) => event.stopPropagation()}><button className="close" onClick={() => setSelected(null)}>×</button><div className="addon-icon large">{selected.name.slice(0, 1)}</div><p className="eyebrow">{selected.category} · {selected.status}</p><h2>{selected.name}</h2><p>{selected.description}</p><div className="detail-meta"><span>Latest release <strong>v{selected.version}</strong></span><span>Downloads <strong>{selected.downloads}</strong></span></div><button className="download">Download latest <span>↓</span></button><p className="fineprint">Release details, dependencies, source links, and author support will appear here.</p></aside></div>}
  </div>;
}
createRoot(document.getElementById('root')!).render(<App />);
